spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/361754100/configserver.git
          search-paths: src/main/resources/configs
          username: 361754100@qq.com
          password: 13751823091.jian

server:
  port: 7001

